//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourcefr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcefr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Properties.Resourcefr", typeof(Resourcefr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une extension de fichiers.
        /// </summary>
        internal static string Btn_AddFileType {
            get {
                return ResourceManager.GetString("Btn_AddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un processus.
        /// </summary>
        internal static string Btn_AddProcess {
            get {
                return ResourceManager.GetString("Btn_AddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un processus.
        /// </summary>
        internal static string Btn_DeleteProcess {
            get {
                return ResourceManager.GetString("Btn_DeleteProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une extension de fichiers.
        /// </summary>
        internal static string Btn_DeleteType {
            get {
                return ResourceManager.GetString("Btn_DeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le serveur.
        /// </summary>
        internal static string Btn_Server {
            get {
                return ResourceManager.GetString("Btn_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string Btn_ThreadAbord {
            get {
                return ResourceManager.GetString("Btn_ThreadAbord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une sauvegarde.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer la sauvegarde.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Processus bloqués.
        /// </summary>
        internal static string CurProcess {
            get {
                return ResourceManager.GetString("CurProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde différentielle.
        /// </summary>
        internal static string Differential_Backup {
            get {
                return ResourceManager.GetString("Differential_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour démarrer, mettre en pause ou arrêter un travail de sauvegarde, sélectionnez le(s) travail(s) de sauvegarde dans la liste puis appuyez sur le bouton de votre choix.
        /// </summary>
        internal static string explanation {
            get {
                return ResourceManager.GetString("explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions de fichiers prioritaires.
        /// </summary>
        internal static string File_Ext {
            get {
                return ResourceManager.GetString("File_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde complète.
        /// </summary>
        internal static string Full_Backup {
            get {
                return ResourceManager.GetString("Full_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        internal static string langLabel {
            get {
                return ResourceManager.GetString("langLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des sauvegardes.
        /// </summary>
        internal static string ListBackUp {
            get {
                return ResourceManager.GetString("ListBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la sauvegarde.
        /// </summary>
        internal static string nameBackup {
            get {
                return ResourceManager.GetString("nameBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le fichier d&apos;état.
        /// </summary>
        internal static string OpenStateFile {
            get {
                return ResourceManager.GetString("OpenStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reprendre.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer la sauvegarde.
        /// </summary>
        internal static string RunBackup {
            get {
                return ResourceManager.GetString("RunBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer en séquentielle.
        /// </summary>
        internal static string RunSequBackup {
            get {
                return ResourceManager.GetString("RunSequBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier source.
        /// </summary>
        internal static string SFLabel {
            get {
                return ResourceManager.GetString("SFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier destination.
        /// </summary>
        internal static string TFLabel {
            get {
                return ResourceManager.GetString("TFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du processus.
        /// </summary>
        internal static string TFLabel_Copy {
            get {
                return ResourceManager.GetString("TFLabel_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier de la dernière sauvegarde complète.
        /// </summary>
        internal static string TFLabel_Copy1 {
            get {
                return ResourceManager.GetString("TFLabel_Copy1", resourceCulture);
            }
        }
    }
}
